version: "2"
services:

  selenium:
    build: ./selenium
    ports:
      - 4444:4444
      - 5900:5900
    tty: true
    networks:
      default:
        aliases:
          - local.selenium
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: ./python
    ports:
      - 8000:8000
    volumes:
      - ./python:/home/workspace
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webnium
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      default:
        aliases:
          - local.mysql
  phpmyadmin:
    depends_on:
      - mysql
    links:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 13306:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin